---
kind: pipeline
type: docker
name: default-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: get-version
  image: debian:bullseye-slim
  commands:
  - "apt-get update"
  - "APPVERSION=$(apt-cache policy unbound | sed -n -e 's/^.*Candidate: //p' | cut -d'-' -f1 | tr -d '\n')"
  - "echo $APPVERSION,latest > .tags"
- name: build
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    repo: linutux/unbound
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

trigger:
  branch:
  - master
  event:
  - push
---
kind: signature
hmac: a428200f90e6ae86db8d3751201a84f3608229dcfa062144a4505a40b9587be9

...
