---
kind: pipeline
type: docker
name: default-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: get-version
  image: debian:buster-slim
  commands:
  - UNBOUND=$(apt-cache policy | sed -n -e 's/^.*Candidate: //p' | cut -d'-' -f1)
  - echo ${UNBOUND},latest > .tags
- name: build
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    repo: linutux/unbound
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

trigger:
  branch:
  - master
  event:
  - push
---
kind: signature
hmac: 24b51d41f2436eb297f3fb9bc0ce217434a068416d87080f8c2d236c8984b01c

...
