kind: pipeline
type: docker
name: default-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    tags: 1.9.0-linux-arm64
    repo: linutux/unbound
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

trigger:
  branch:
  - master
  event:
  - push

---
kind: pipeline
type: docker
name: default-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    tags: 1.9.0-linux-amd64
    repo: linutux/unbound
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

trigger:
  branch:
  - master
  event:
  - push
---
kind: pipeline
type: docker
name: manifest

steps:
- name: manifest
  image: plugins/manifest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    target: linutux/unbound:1.9.0
    template: linutux/unbound:1.9.0-OS-ARCH
    platforms:
      - linux/arm64
      - linux/amd64
    ignore-missing: true

- name: manifest-latest
  image: plugins/manifest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    target: linutux/unbound:latest
    template: linutux/unbound:1.9.0-OS-ARCH
    platforms:
      - linux/arm64
      - linux/amd64
    ignore-missing: true
---
kind: signature
hmac: 341f1e89a6709fcd429f68500f4c1fa9543f54ac05684d26ece221e2ad0c488a

...
