global_variables:
  unbound_tag: &unbound_tag 0.0.1

kind: pipeline
type: docker
name: default-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    tags: !concat [*unbound_tag, "-linux-arm64"]
    repo: linutux/unbound
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

trigger:
  branch:
  - master
  event:
  - push

---
global_variables:
  unbound_tag: &unbound_tag 0.0.1

kind: pipeline
type: docker
name: default-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    tags: !concat [*unbound_tag, "-linux-amd64"]
    repo: linutux/unbound
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

trigger:
  branch:
  - master
  event:
  - push
---
kind: pipeline
type: docker
name: manifest

steps:
- name: manifest
  image: plugins/manifest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: manifest.tmpl
      tags: latest
