---
kind: pipeline
type: docker
name: default-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: get-version
  image: debian:buster-slim
  commands:
  - "UNBOUND=`apt-cache policy | sed -n -e 's/^.*Candidate: //p' | cut -d'-' -f1 | tr -d'\n'`"
  - "echo ${UNBOUND},latest > .tags"
- name: build
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    repo: linutux/unbound
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

trigger:
  branch:
  - master
  event:
  - push
---
kind: signature
hmac: 43993b035a92d895768d531ec61c89693e1a2fa07ff64aafc5f3a8c03e91868d

...
