kind: pipeline
type: docker
name: default-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    tags: 0.0.1-linux-arm64
    repo: linutux/unbound
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

trigger:
  branch:
  - master
  event:
  - push

---
kind: pipeline
type: docker
name: default-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    tags: 0.0.1-linux-amd64
    repo: linutux/unbound
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

trigger:
  branch:
  - master
  event:
  - push
---
kind: pipeline
type: docker
name: manifest

steps:
- name: manifest
  image: plugins/manifest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    target: linutux/unbound:0.0.1
    template: linutux/unbound:0.0.1-OS-ARCH
    platforms:
      - linux/arm64
      - linux/amd64
